import "@/styles/globals.css";

import { Metadata } from "next";
import { ReactElement } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body> */}
      <body>{children as ReactElement}</body>
      {/* </body> */}
    </html>
  );
}
